openapi: 3.0.0
info:
  title: Planet Square API
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api/v1'
paths:
  /health:
    get:
      summary: 헬스 체크
      operationId: healthCheck
      tags:
        - Health
      responses:
        '200':
          description: 정상 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '500':
          description: 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /country/csv:
    post:
      summary: 국가 정보 csv를 이용한 등록
      operationId: countryCsvRegister
      tags:
        - Country
      responses:
        '200':
          description: 정상 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryCsvRegisterResponse'
        '500':
          description: 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      description: 에러 응답
      properties:
        message:
          type: string
          description: 에러 메시지
        timestamp:
          type: string
          description: 에러 발생 시각
    HealthResponse:
      type: object
      description: 헬스 체크 응답
      properties:
        status:
          type: string
    CountryCsvRegisterResponse:
      type: object
      description: Csv를 이용한 저장 정보
      properties:
        total:
          type: integer
        failed:
          type: integer
