openapi: 3.0.0
info:
  title: Planet Square API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1

paths:
  /health:
    $ref: './paths/health.yaml#/health'

components:
  schemas:
    ErrorResponse:
      $ref: './components/common/ErrorResponse.yaml'
    HealthResponse:
      $ref: './components/common/HealthResponse.yaml'